version: 1.2
workflows:
   - name: sha256_cwl
     subclass: CWL
     primaryDescriptorPath: /sha256.cwl
     filters:
         branches:
             - master
   - name: sha256_wdl
     subclass: WDL
     primaryDescriptorPath: /sha256.wdl
     filters:
         branches:
             - master
